-- Ensure password_otp table has all required columns for email changes
CREATE TABLE IF NOT EXISTS public.password_otp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    otp TEXT NOT NULL,
    purpose TEXT NOT NULL,
    attempts INTEGER DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add missing columns if table already exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='password_otp' AND column_name='email') THEN
        ALTER TABLE public.password_otp ADD COLUMN email TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='password_otp' AND column_name='attempts') THEN
        ALTER TABLE public.password_otp ADD COLUMN attempts INTEGER DEFAULT 0;
    END IF;
END $$;