-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS TABLE
create table if not exists public.users (
  id uuid primary key,
  username text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROOMS TABLE
create table if not exists public.rooms (
  id text primary key, -- Room codes are text (e.g. "RL09U3")
  title text,
  room_type text default 'meeting',
  owner_id uuid references public.users(id),
  is_private boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROOM MEMBERS TABLE
create table if not exists public.room_members (
  id bigint generated by default as identity primary key,
  room_id text references public.rooms(id) on delete cascade,
  user_id uuid references public.users(id),
  role text default 'participant',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  left_at timestamp with time zone,
  unique(room_id, user_id)
);

-- MESSAGES TABLE
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id text references public.rooms(id) on delete cascade,
  sender_id uuid references public.users(id),
  message_type text default 'text',
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FEEDBACK TABLE
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  type text not null, -- 'bug', 'feature', etc.
  rating integer,
  message text not null,
  name text,
  email text,
  subject text,
  user_id uuid references public.users(id), -- Optional, link to user if logged in
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES (Optional - Basic Security)
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.messages enable row level security;

-- Allow public read access (for demo simplicity, refine for prod)
-- Allow public read access (for demo simplicity, refine for prod)
drop policy if exists "Public users are viewable by everyone" on public.users;
create policy "Public users are viewable by everyone" on public.users for select using (true);

drop policy if exists "Public rooms are viewable by everyone" on public.rooms;
create policy "Public rooms are viewable by everyone" on public.rooms for select using (true);

drop policy if exists "Members are viewable by everyone" on public.room_members;
create policy "Members are viewable by everyone" on public.room_members for select using (true);

drop policy if exists "Messages are viewable by everyone" on public.messages;
create policy "Messages are viewable by everyone" on public.messages for select using (true);

-- Allow public inserts for feedback (anonymous users allowed)
alter table public.feedback enable row level security;
drop policy if exists "Anyone can insert feedback" on public.feedback;
create policy "Anyone can insert feedback" on public.feedback for insert with check (true);

drop policy if exists "Feedback viewable by everyone" on public.feedback;
create policy "Feedback viewable by everyone" on public.feedback for select using (true);

drop policy if exists "Anyone can delete feedback" on public.feedback;
create policy "Anyone can delete feedback" on public.feedback for delete using (true);

-- Allow inserts (adjusted for service role usage which bypasses RLS, but meaningful for client direct access)
drop policy if exists "Users can insert their own profile" on public.users;
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);

-- FRIEND REQUESTS TABLE
create table if not exists public.friend_requests (
  id uuid primary key default uuid_generate_v4(),
  from_user_id uuid not null,
  to_user_id uuid not null,
  status text not null check (status in ('pending','accepted','declined','cancelled')),
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  responded_at timestamp with time zone
);

create index if not exists idx_friend_requests_to_user
  on public.friend_requests(to_user_id, status);

-- FRIENDS TABLE
create table if not exists public.friends (
  user_id uuid not null,
  friend_id uuid not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, friend_id)
);

create index if not exists idx_friends_friend_id
  on public.friends(friend_id);
