-- Migration: Advanced Room Settings
-- Created: 2026-03-07
-- 1. Room Settings Table
CREATE TABLE IF NOT EXISTS public.room_settings (
    room_id TEXT PRIMARY KEY REFERENCES public.rooms(id) ON DELETE CASCADE,
    invite_only BOOLEAN DEFAULT false,
    join_by_link BOOLEAN DEFAULT true,
    join_by_code BOOLEAN DEFAULT true,
    host_only_code_visibility BOOLEAN DEFAULT false,
    waiting_lobby BOOLEAN DEFAULT false,
    organization_only BOOLEAN DEFAULT false,
    host_controlled_speaking BOOLEAN DEFAULT false,
    chat_permission TEXT DEFAULT 'everyone' CHECK (
        chat_permission IN ('everyone', 'host_only', 'none')
    ),
    encryption_enabled BOOLEAN DEFAULT false,
    ai_moderation_level TEXT DEFAULT 'off' CHECK (
        ai_moderation_level IN ('off', 'passive', 'active')
    ),
    auto_close_minutes INTEGER DEFAULT 0,
    hidden_room BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 2. Room Lobby Table
CREATE TABLE IF NOT EXISTS public.room_lobby (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT REFERENCES public.rooms(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    UNIQUE(room_id, user_id)
);
-- 3. Room Speakers Table
CREATE TABLE IF NOT EXISTS public.room_speakers (
    room_id TEXT REFERENCES public.rooms(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    allowed BOOLEAN DEFAULT true,
    PRIMARY KEY (room_id, user_id)
);
-- 4. Room Codes Table (Rotatable)
CREATE TABLE IF NOT EXISTS public.room_codes (
    room_id TEXT PRIMARY KEY REFERENCES public.rooms(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Enable RLS
ALTER TABLE public.room_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_lobby ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_speakers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_codes ENABLE ROW LEVEL SECURITY;
-- Policies for room_settings
CREATE POLICY "Settings viewable by room members" ON public.room_settings FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.room_members rm
            WHERE rm.room_id = room_settings.room_id
                AND rm.user_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1
            FROM public.rooms r
            WHERE r.id = room_settings.room_id
                AND r.owner_id = auth.uid()
        )
    );
CREATE POLICY "Settings updateable by owner" ON public.room_settings FOR
UPDATE USING (
        EXISTS (
            SELECT 1
            FROM public.rooms r
            WHERE r.id = room_settings.room_id
                AND r.owner_id = auth.uid()
        )
    );
-- Policies for room_lobby
CREATE POLICY "Lobby viewable by host" ON public.room_lobby FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.rooms r
            WHERE r.id = room_lobby.room_id
                AND r.owner_id = auth.uid()
        )
        OR user_id = auth.uid()
    );
CREATE POLICY "Users can request to join" ON public.room_lobby FOR
INSERT WITH CHECK (user_id = auth.uid());
-- Policies for room_speakers
CREATE POLICY "Speakers viewable by room members" ON public.room_speakers FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.room_members rm
            WHERE rm.room_id = room_speakers.room_id
                AND rm.user_id = auth.uid()
        )
    );
-- Policies for room_codes
CREATE POLICY "Codes viewable by host" ON public.room_codes FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.rooms r
            WHERE r.id = room_codes.room_id
                AND r.owner_id = auth.uid()
        )
        OR EXISTS (
            SELECT 1
            FROM public.room_settings rs
            WHERE rs.room_id = room_codes.room_id
                AND rs.host_only_code_visibility = false
        )
    );